### ISSUE TITLE
Slider project not setup for for continuous integration (Travis)

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-slider#29]
Hi Em,

You seem to be the best person to do this quickly - so we can release asap.
Could you take care of it?

**Comment by robincover** [comment]
Noted (if relevant) https://travis-ci.org/oasis-open/cti-stix-slider

**Comment by rpiazza** [comment]
Wow - not enough coffee.  The project that isn't set up for continuous integration is mitre/cti.
