### ISSUE TITLE
Convert object of type "identity"

### ISSUE THREAD

**Issue by cyberfox1** [oasis-open/cti-stix-slider#30]
It seems that object of type "identity" are not converted to Stix1.

It may be because the STIXPackage class from the base Stix1 library does not appear to have any ability to add identity information.

**Comment by rpiazza** [comment]
The closest match for STIX 2.0 Identity is the STIX 1.x Information Source.

STIXPackage does not directly have an Information Source property, but STIXHeader does.

@cyberfox1, can you be a little more explicit about your concerns, or send an example of some content that you think the slider converts poorly?

**Comment by cyberfox1** [comment]
@rpiazza thanks for the tip - I ended up adding the Identity to an InformationSource, and then setting that to the producer field of a new Indicator.

If I can make a suggestion, it would be nice if the Slider library had a callback API that would be called for objects the Slider does not know how to convert - and the callback would be passed the object and the STIXPackage object so it can convert and add the object itself.

**Comment by rpiazza** [comment]
This is a great idea - for both the elevator and slider.  We will look into it.
