### ISSUE TITLE
Namespace is hardcoded as "example"

### ISSUE THREAD

**Issue by cyberfox1** [oasis-open/cti-stix-slider#32]
In convert_stix.py, the Stix namespace is hardcoded as a global variable _ID_NAMESPACE to "example". This is then bound to several string building functions, and cannot be overridden as they refer to the variable directly, not through a package/module. 

It would be good to change this value dynamically at runtime, which is not currently possible.

I would suggest defining the variable in stix2slider/__init__.py so functions can refer to stix2slider._ID_NAMESPACE to both change and retrieve the value.

**Comment by rpiazza** [comment]
Thanks @cyberfox1, this is a good idea.

I was thinking of an command line option, would that work for you?

**Comment by cyberfox1** [comment]
Hi @rpiazza , actually I am integrating the library into a web server currently using the to_string(?), so part of the API interface would be preferred. Although, if it was simply a module variable that can be changed before to_string is called would be fine.

**Comment by rpiazza** [comment]
I assume you mean "slide_string"?  How do you set up the options currently??

**Comment by cyberfox1** [comment]
@rpiazza yes slide_string. Actually I am not passing in any options, its not entirely clear how to pass options using the library API as option handling seems to be based around CLI parsing...I know there is a lower level "sdv" library which might expose more options but I haven't used it directly yet.

**Comment by rpiazza** [comment]
Look in options.py.  There are 3 methods you might want to use:

- initialize_options (with None)
- get_option_value
- set_option_value

So with this new option, you could use these methods to set the namespace.  Does that work for you?

**Comment by cyberfox1** [comment]
@rpiazza OK thanks I'll look at that. And yes, if that allows setting the namespace for slide_string that would work for me, thanks.

**Comment by cyberfox1** [comment]
Hi @rpiazza , I found there is another location in mixbox that has a hardcoded "example" namespace. To make it customizable, in idgen.py I moved EXAMPLE_NAMESPACE into \_\_init\_\_.py, and then changed the \_\_init\_\_ method of IDGenerator to the following:

mixbox/idgen.py:

       def __init__(self, namespace=None, method=METHOD_UUID):
          self.namespace = namespace if namespace else mixbox.EXAMPLE_NAMESPACE

**Comment by rpiazza** [comment]
@emmanvg, can you look into this?

**Comment by gtback** [comment]
Probably want to look at [`mixbox.idgen.set_id_namespace`](https://github.com/CybOXProject/mixbox/blob/76a85b89eb04be3c189761dad9e5e3a83a620258/mixbox/idgen.py#L95), and expose a method in the slider to set that.

**Comment by emmanvg** [comment]
@cyberfox1, I looked into this and I have added a new argument called `--use-namespace`. You would use it like this: `stix2_slider <file> --use-namespace="example http://example.com"` if you are invoking the CLI. If you are using the slider as a library, you can do so from by calling using the following methods:

- initialize_options()
- set_option_value("use_namespace", "example http://example.com")

**Comment by cyberfox1** [comment]
@emmanvg thanks that looks good, I will try and test this change.
