### ISSUE TITLE
python-cybox's win_user_object.py was renamed

### ISSUE THREAD

**Issue by S03D4-164** [oasis-open/cti-stix-slider#45]
A module which uses stix2slider got following error:
```
  File "/home/user/venv2/lib/python3.7/site-packages/stix2slider/convert_cyber_observables.py", line 55, in <module>
    from cybox.objects.win_user_object import UserAccount, WinUser                                                                                                                                                
ModuleNotFoundError: No module named 'cybox.objects.win_user_object' 
```
I checked python-cybox and found that win_user_object.py was renamed to win_user_account_object.py  recently.

**Comment by rpiazza** [comment]
@S03D4-164 

There will be a new release of the slider released very soon which will fix this.  I assume you just updated to the latest python-cybox?  If you revert back to the previous version, the slider should work again.  Sorry for the inconvenience.

**Comment by S03D4-164** [comment]
Thank you for your reply. I'll wait for the update.
